# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'DAI'
# The slogan describes your website and is used on homepage in <title> and other important places
slogan: 'slogan'
# Logo size is 600x80 pixels
logo: "logo.png"
permalink: /:title.html

exclude: [ ".gitignore", "README.md", "CNAME" ]

email: daishiwen1212@gmail.com
description: "Java/Android/Emotion/Diary/Journey/Template, Welcome."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daishiwen.github.io" # the base hostname & protocol for your site
urlimg: "http://daishiwen.github.io/images/"
# url: "http://localhost:4000" # the base hostname & protocol for your site
# urlimg: "http://localhost:4000/images/"
github_username: daishiwen

# Build settings
markdown: kramdown
highlighter: pygments

sass:
    style: :compressed

#       ______            _
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  )
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/
#
# Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
# More information » https://mathiasbynens.be/notes/touch-icons

favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication-TileImage:                'apple-touch-icon-144x144-precomposed.png' # Size 144x144
msapplication-TileColor:                '#F44336'

#        ____  _
#       / __ \(_)________ ___  _______
#      / / / / / ___/ __ `/ / / / ___/
#     / /_/ / (__  ) /_/ / /_/ (__  )
#    /_____/_/____/\__, /\__,_/____/
#                    /_/
#
# used in _includes/_disqus.html

disqus_shortname: daishiwen

#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/
#                        /____/
#
# https://www.google.com/analytics/
# used in _includes/_footer_scripts.html

google_analytics_tracking_id: UA-78383065-1
